name: "build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ released ]

jobs:
  call-build:
    uses: "jpenilla/actions/.github/workflows/shared-ci.yml@master"
    secrets: inherit
    with:
      hangar-publish: true
      modrinth-publish: true
      init-submodules: true
      artifacts-path: 'build/libs/*-all.jar'
      jdk-version: 21
